function structureSaver(app)
    DEERefineSturctureFileName = "DEERefineSturcture.mat";
    DEERefineSturcture = struct('structureIndexEachScript', app.structureIndexEachScript,...
                                'runFileName', app.runFileName, ...
                                'maximalClashes', app.maximalClashes, ...
                                'monteCarloIteration', app.monteCarloIteration, ...
                                'RMSE', app.RMSE, ...
                                'initialStructureFullPath', app.initialStructureFileName, ...
                                'phiPsiAngle', app.phiPsiAngle, ...
                                'flexiblePhiPsiIndex', app.flexiblePhiPsiIndex, ...
                                'targetNumberStructure', app.numberOfStructure, ...
                                'distanceDistributionFullPath', app.distanceDistributionFileName, ...
                                'PDBEvolution', app.PDBEvolution);
    save(DEERefineSturctureFileName, '-struct', 'DEERefineSturcture');
    

end