function appendingDEERRefineRestraintsTable(app)
    app.DEERRefineRestraintsTable.Data = [app.DEERRefineRestraintsTable.Data;...
                                          sprintf("%d", app.numberOfTimesPrLoadingButtonHit) ...
                                          sprintf("%d", app.spinPairResidue1(app.numberOfTimesPrLoadingButtonHit)) ...
                                          sprintf("%d", app.spinPairResidue2(app.numberOfTimesPrLoadingButtonHit)) ...
                                          sprintf("%.2f", app.distanceDistributionTarger(app.numberOfTimesPrLoadingButtonHit))];
end